version: '3.7'

services:
  redis:
    image: redis
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'booking'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - mysql:/var/lib/mysql
  app:
    image: "ghcr.io/tullinge/booking:latest"
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      REDIS_HOST: 'redis'
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
      GSUITE_DOMAIN_NAME: '${GSUITE_DOMAIN_NAME}' 
      PORT: "${PORT}"
    depends_on:
      - mysql
      - redis
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    expose:
      - "${PORT}"

volumes:
  mysql:
